config/routes.rb
Rails.application.routes.draw do
  
  resources :scores
  resources :users

  root 'game#index'

  get    '/login',        to: 'sessions#new'
  post   '/login',        to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  get    '/signup',       to: 'users#new'
  post   '/signup',       to: 'users#create'
  get    '/about',        to: 'static_pages#about'
  get    '/contact',      to: 'static_pages#contact'
  get    '/leaderboard',  to: 'scores#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :scores

  validates :username, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController

  skip_before_action :authorized, only: :index

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[ show edit update destroy ]

  # GET /scores or /scores.json
  def index
    @scores = Score.all.order(value: :desc).first(10)
  end

  # GET /scores/1 or /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to score_url(@score), notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to score_url(@score), notice: "Score was successfully updated." }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url, notice: "Score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:value, :user_id, :date, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    destination = '/login';
    @user = User.find_by(username: params[:username])
    if !@user
      flash[:error] = 'Invalid username'
    elsif !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      destination = '/'
    else
      flash[:error] = 'Invalid password'
    end
      redirect_to destination, error: flash[:error]
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  skip_before_action :authorized, only: [:about, :contact]

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :authorized, only: [:new, :create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/game/index.html.erb
<div class="game">
  <canvas id="canvas" width="300" height="573"> 
    Your browser does not support the HTML5 canvas tag.
  </canvas>

  <br><br>
  <p>⬅️ &nbsp;➡️ &nbsp;⬇️ &nbsp;to move block<br>⬆️ &nbsp;to rotate block<br>no touchscreen controls yet</p>
  <p>code on <a href="https://github.com/mark-mcdermott/emoji-tetrominos">github</a></p>
  <p>a work in progress</p>
</div>

<script src="<%= asset_path("emoji-tetrominos.js") %>" ></script>

app/views/home/index.html.erb
<h1>test</h1>


<canvas id="canvas" width="300" height="573"></canvas>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Markmcdapp125</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <% if Rails.env.development? %>
      <%= javascript_include_tag "hotwire-livereload", defer: true %>
    <% end %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/shared/header' %>
        <div class="p-5 mb-4 bg-light rounded-3">
          <div class="container-fluid pb-5">
            <%= yield %>
          </div>
        </div>
      <%= render 'layouts/shared/footer' %>
    </div>
    
  </body>

</html>

app/views/layouts/shared/_flash-messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/shared/_footer.html.erb
    <footer class="pt-3 mt-4 text-muted border-top">
      &copy; <%= Time.zone.now.year %>
    </footer>

app/views/layouts/shared/_header.html.erb
    <header class="pb-4 my-4 border-bottom">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <i class="bi bi-joystick navbar-brand-icon"></i>
          <%= link_to 'Emoji Tetris', '/', class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item"><%= link_to 'Home', '/', class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'About', '/about', class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to 'Leaderboard', '/leaderboard', class: 'nav-link' %></li>
              <% if logged_in? %>
                <li class="nav-item"><%= link_to 'Users', '/users', class: 'nav-link' %></li>
              <% end %>
              <li class="nav-item"><%= link_to 'Contact', '/contact', class: 'nav-link' %></li>

              <% if !logged_in? %>
                <li class="nav-item"><%= link_to 'Log in', '/login', class: 'nav-link' %></li>
              <% else %>
                <li class="nav-item"><%= link_to 'Log out', '/login', method: :delete, class: 'nav-link' %></li>
              <% end %>
              <% if !logged_in? %>
                <li class="nav-item"><%= link_to 'Sign up', '/signup', method: :delete, class: 'nav-link' %></li>
              <% end %>

          </div>
        </div>
      </nav>
    </header>

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.number_field :value %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/_score.html.erb
<div id="<%= dom_id score %>">
  <p>
    <strong>Value:</strong>
    <%= score.value %>
  </p>

  <p>
    <strong>User:</strong>
    <%= User.find_by_id(score.user_id).username %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= score.date %>
  </p>

</div>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Show this score", @score %> |
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Leaderboard</h1>

<div id="scores" class="col-md-6">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">score</th>
        <th scope="col">user</th>
        <th scope="col">date</th>
      </tr>
    </thead>
    <tbody>
      <% @scores.each_with_index do |score, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= score.value  %></td>
          <td><%= User.find_by_id(score.user_id).username %></td>
          <td><%= score.date.strftime('%-m/%-d/%y') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- <%= link_to "New score", new_score_path %> -->

app/views/scores/new.html.erb
<h1>New score</h1>

<%= render "form", score: @score %>

<br>

<div>
  <%= link_to "Back to scores", scores_path %>
</div>

app/views/scores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @score %>

<div>
  <%= link_to "Edit this score", edit_score_path(@score) %> |
  <%= link_to "Back to scores", scores_path %>

  <%= button_to "Destroy this score", @score, method: :delete %>
</div>

app/views/static_pages/about.html.erb
<h1>About</h1>

<p>A javascript Emoji Tetris game was an idea I had about five years ago. <a target="_blank" href="https://github.com/William-Olson">William Olson</a> helped me work through technical implementation issues and helped me with my javascript skills. We got it to a working, but somewhat unpolished state. Then I got busy with grad school and it sat untouched until now. I always wanted to create a leaderboard for it, where people could log in and their scores would be saved and posted to a leaderboard. Finally got around to it now with this iteration while learning Rails.</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

[Contact page here]

app/views/users/_form.html.erb
<%= form_with(model: user, class: 'page-form') do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-danger">
      <p><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</p>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit 'Sign up' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="card mt-4" id="<%= dom_id user %>" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-text"><%= user.username %></h5>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">

  <!-- <%= link_to "New user", new_user_path, class: 'btn btn-primary' %> -->

  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user, class: 'btn btn-secondary btn-sm my-2' %>
    </p>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path, class: 'btn btn-secondary' %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div class="mt-3">
  <%= link_to "Edit this user", edit_user_path(@user), class: 'btn btn-primary' %>
  <%= link_to "Back to users", users_path, class: 'btn btn-secondary' %>
  <%= button_to "Destroy this user", @user, method: :delete, class: 'btn btn-danger' %>
</div>